from Aircraft import Aircraft, DREF, DREF_TYPE

class Toliss_A319(Aircraft):
    def set_name(self, name):
        self.name = name

    def create_aircraft(self):
        #name = "test"
        print("Test")
        self.drefs = []
        self.drefs.append(DREF("MACH", "toliss_airbus/ias_mach_button_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("LOC", "AirbusFBW/LOCbutton", DREF_TYPE.CMD))
        self.drefs.append(DREF("TRK", "toliss_airbus/hdgtrk_button_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("AP1", "AirbusFBW/AP1Engage", DREF_TYPE.DATA))
        self.drefs.append(DREF("AP2", "AirbusFBW/AP2Engage", DREF_TYPE.DATA))
        self.drefs.append(DREF("A/THR", "AirbusFBW/ATHRbutton", DREF_TYPE.CMD))
        self.drefs.append(DREF("EXPED", "AirbusFBW/EXPEDbutton", DREF_TYPE.CMD))
        self.drefs.append(DREF("METRIC", "toliss_airbus/metric_alt_button_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("APPR", "AirbusFBW/APPRbutton", DREF_TYPE.CMD))
        self.drefs.append(DREF("SPD DEC", "sim/autopilot/airspeed_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("SPD INC", "sim/autopilot/airspeed_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("SPD PUSH", "AirbusFBW/PushSPDSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("SPD PULL", "AirbusFBW/PullSPDSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("HDG DEC", "sim/autopilot/heading_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("HDG INC", "sim/autopilot/heading_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("HDG PUSH", "AirbusFBW/PushHDGSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("HDG PULL", "AirbusFBW/PullHDGSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("ALT DEC", "sim/autopilot/altitude_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("ALT INC", "sim/autopilot/altitude_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("ALT PUSH", "AirbusFBW/PushAltitude", DREF_TYPE.CMD))
        self.drefs.append(DREF("ALT PULL", "AirbusFBW/PullAltitude", DREF_TYPE.CMD))
        self.drefs.append(DREF("VS DEC", "sim/autopilot/vertical_speed_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("VS INC", "sim/autopilot/vertical_speed_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("VS PUSH", "AirbusFBW/PushVSSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("VS PULL", "AirbusFBW/PullVSSel", DREF_TYPE.CMD))
        self.drefs.append(DREF("ALT 100", "AirbusFBW/ALT100_1000", DREF_TYPE.DATA))
        self.drefs.append(DREF("ALT 1000", "AirbusFBW/ALT100_1000", DREF_TYPE.DATA))
        self.drefs.append(DREF("BRIGHT", "AirbusFBW/SupplLightLevelRehostats[0]", DREF_TYPE.DATA))
        self.drefs.append(DREF("BRIGHT_LCD", "AirbusFBW/SupplLightLevelRehostats[1]", DREF_TYPE.DATA))
        self.drefs.append(DREF("APPR_LED", "AirbusFBW/APPRilluminated", DREF_TYPE.DATA))
        self.drefs.append(DREF("ATHR_LED", "AirbusFBW/ATHRmode", DREF_TYPE.DATA))
        self.drefs.append(DREF("LOC_LED", "AirbusFBW/LOCilluminated", DREF_TYPE.DATA))

        self.drefs.append(DREF("HDGdashed", "AirbusFBW/HDGdashed", DREF_TYPE.DATA))
        self.drefs.append(DREF("SPDdashed", "AirbusFBW/SPDdashed", DREF_TYPE.DATA))
        self.drefs.append(DREF("VSdashed", "AirbusFBW/VSdashed", DREF_TYPE.DATA))
        self.drefs.append(DREF("airspeed", "sim/cockpit/autopilot/airspeed", DREF_TYPE.DATA))
        self.drefs.append(DREF("airspeed_dial_kts_mach", "sim/cockpit2/autopilot/airspeed_dial_kts_mach", DREF_TYPE.DATA))
        self.drefs.append(DREF("SPDmanaged", "AirbusFBW/SPDmanaged", DREF_TYPE.DATA))
        self.drefs.append(DREF("airspeed_is_mach", "sim/cockpit/autopilot/airspeed_is_mach", DREF_TYPE.DATA))
        self.drefs.append(DREF("heading_mag", "sim/cockpit/autopilot/heading_mag", DREF_TYPE.DATA))
        self.drefs.append(DREF("HDGmanaged", "AirbusFBW/HDGmanaged", DREF_TYPE.DATA))
        self.drefs.append(DREF("HDGTRKmode", "AirbusFBW/HDGTRKmode", DREF_TYPE.DATA))
        self.drefs.append(DREF("altitude", "sim/cockpit/autopilot/altitude", DREF_TYPE.DATA))
        self.drefs.append(DREF("ALTmanaged", "AirbusFBW/ALTmanaged", DREF_TYPE.DATA))
        self.drefs.append(DREF("vertical_velocity", "sim/cockpit/autopilot/vertical_velocity", DREF_TYPE.DATA))
        self.drefs.append(DREF("fpa", "sim/cockpit2/autopilot/fpa", DREF_TYPE.DATA))
        self.drefs.append(DREF("APVerticalMode", "AirbusFBW/APVerticalMode", DREF_TYPE.DATA))
        self.drefs.append(DREF("barometer_setting_in_hg_copilot", "sim/cockpit2/gauges/actuators/barometer_setting_in_hg_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("barometer_setting_in_hg_pilot", "sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("BaroStdFO", "AirbusFBW/BaroStdFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("BaroUnitFO", "AirbusFBW/BaroUnitFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("BaroStdCapt", "AirbusFBW/BaroStdCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("BaroUnitCapt", "AirbusFBW/BaroUnitCapt", DREF_TYPE.DATA))

        #TODO: device_config & DEVICEMASK.EFISR
        self.drefs.append(DREF("R_FD", "toliss_airbus/fd2_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_LS", "toliss_airbus/dispcommands/CoLSButtonPush", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_CSTR", "toliss_airbus/dispcommands/CoCstrPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_WPT", "toliss_airbus/dispcommands/CoWptPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_VOR.D", "toliss_airbus/dispcommands/CoVorDPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_NDB", "toliss_airbus/dispcommands/CoNdbPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_ARPT", "toliss_airbus/dispcommands/CoArptPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_STD PUSH", "toliss_airbus/copilot_baro_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_STD PULL", "toliss_airbus/copilot_baro_pull", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_PRESS DEC", "sim/instruments/barometer_copilot_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_PRESS INC", "sim/instruments/barometer_copilot_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("R_inHg", "AirbusFBW/BaroUnitFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_hPa", "AirbusFBW/BaroUnitFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_MODE LS", "AirbusFBW/NDmodeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_MODE VOR", "AirbusFBW/NDmodeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_MODE NAV", "AirbusFBW/NDmodeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_MODE ARC", "AirbusFBW/NDmodeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_MODE PLAN", "AirbusFBW/NDmodeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 10", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 20", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 40", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 80", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 160", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_RANGE 320", "AirbusFBW/NDrangeFO", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_1 VOR", "sim/cockpit2/EFIS/EFIS_1_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_1 OFF", "sim/cockpit2/EFIS/EFIS_1_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_1 ADF", "sim/cockpit2/EFIS/EFIS_1_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_2 VOR", "sim/cockpit2/EFIS/EFIS_2_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_2 OFF", "sim/cockpit2/EFIS/EFIS_2_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_2 ADF", "sim/cockpit2/EFIS/EFIS_2_selection_copilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("R_ARPT_IND", "AirbusFBW/NDShowARPTFO", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_NDB_IND", "AirbusFBW/NDShowNDBFO", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_VORD_IND", "AirbusFBW/NDShowVORDFO", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_WPT_IND", "AirbusFBW/NDShowWPTFO", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_CSTR_IND", "AirbusFBW/NDShowCSTRFO", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_FD_IND", "AirbusFBW/FD2Engage", DREF_TYPE.NONE))
        self.drefs.append(DREF("R_LS_IND", "AirbusFBW/ILSonFO", DREF_TYPE.NONE))

        #TODO: device_config & DEVICEMASK.EFISL
        self.drefs.append(DREF("L_FD", "toliss_airbus/fd1_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_LS", "toliss_airbus/dispcommands/CaptLSButtonPush", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_CSTR", "toliss_airbus/dispcommands/CaptCstrPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_WPT", "toliss_airbus/dispcommands/CaptWptPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_VOR.D", "toliss_airbus/dispcommands/CaptVorDPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_NDB", "toliss_airbus/dispcommands/CaptNdbPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_ARPT", "toliss_airbus/dispcommands/CaptArptPushButton", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_STD PUSH", "toliss_airbus/capt_baro_push", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_STD PULL", "toliss_airbus/capt_baro_pull", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_PRESS DEC", "sim/instruments/barometer_down", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_PRESS INC", "sim/instruments/barometer_up", DREF_TYPE.CMD))
        self.drefs.append(DREF("L_inHg", "AirbusFBW/BaroUnitCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_hPa", "AirbusFBW/BaroUnitCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_MODE LS", "AirbusFBW/NDmodeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_MODE VOR", "AirbusFBW/NDmodeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_MODE NAV", "AirbusFBW/NDmodeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_MODE ARC", "AirbusFBW/NDmodeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_MODE PLAN", "AirbusFBW/NDmodeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 10", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 20", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 40", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 80", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 160", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_RANGE 320", "AirbusFBW/NDrangeCapt", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_1 ADF", "sim/cockpit2/EFIS/EFIS_1_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_1 OFF", "sim/cockpit2/EFIS/EFIS_1_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_1 VOR", "sim/cockpit2/EFIS/EFIS_1_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_2 ADF", "sim/cockpit2/EFIS/EFIS_2_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_2 OFF", "sim/cockpit2/EFIS/EFIS_2_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_2 VOR", "sim/cockpit2/EFIS/EFIS_2_selection_pilot", DREF_TYPE.DATA))
        self.drefs.append(DREF("L_ARPT_IND", "AirbusFBW/NDShowARPTCapt", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_NDB_IND", "AirbusFBW/NDShowNDBCapt", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_VORD_IND", "AirbusFBW/NDShowVORDCapt", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_WPT_IND", "AirbusFBW/NDShowWPTCapt", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_CSTR_IND", "AirbusFBW/NDShowCSTRCapt", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_FD_IND", "AirbusFBW/FD1Engage", DREF_TYPE.NONE))
        self.drefs.append(DREF("L_LS_IND", "AirbusFBW/ILSonCapt", DREF_TYPE.NONE))

acf = Toliss_A319()
acf.set_name("Toliss A319 and compatibla")

acf.create_aircraft()
